
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"  # fpm default
    volumes:
      - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    networks:
      - laravel-net
    command: >
      sh -c "php artisan migrate:refresh --seed &&
        php artisan key:generate && 
        php artisan passport:install &&
        php-fpm"


  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test:
          - CMD
          - mysqladmin
          - ping
          - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
    networks:
      - laravel-net

  node:
    image: node:12-alpine
    platform: linux/amd64
    container_name: laravel-node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"  # para browserSync si usas este puerto
    command: sh -c "npm install && npm run watch"
    networks:
      - laravel-net
    depends_on:
      - app

volumes:
  mysql_data:
networks:
  laravel-net:
    driver: bridge